// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkingWithDB.DBContexts;

#nullable disable

namespace Module4HW4.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220712001141_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorkingWithDB.Models.Teapot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProducingCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teapots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2.2999999999999998,
                            Color = "Black",
                            Manufacturer = "Xiaomi",
                            Material = "Plastic + Metal",
                            Power = 2400,
                            Price = 2199.0,
                            ProducingCountry = "China",
                            Quantity = 10,
                            Title = "Teapot 1",
                            Warranty = 12
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1.5,
                            Color = "Green",
                            Manufacturer = "Xiaomi",
                            Material = "Plastic",
                            Power = 1800,
                            Price = 1899.0,
                            ProducingCountry = "China",
                            Quantity = 5,
                            Title = "Teapot 2",
                            Warranty = 18
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1.8,
                            Color = "White",
                            Manufacturer = "Tefal",
                            Material = "Plastic + Metal",
                            Power = 2400,
                            Price = 2199.0,
                            ProducingCountry = "China",
                            Quantity = 6,
                            Title = "Teapot 3",
                            Warranty = 24
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
